### ISSUE TITLE
Problem with Bootstrap outside CMC

### ISSUE THREAD

**Issue by doylejg** [meteokid/python-rpn#11]
After installing the bootstrap suggested in a closed issue I get the following errors. 

Global tag values: 
ERROR: NO SHORTCUT FOUND FOR /ssm/net/hpcs/201402/02/base
ERROR: NO SHORTCUT FOUND FOR /ssm/net/hpcs/201402/02/intel13sp1u2
ERROR: NO SHORTCUT FOUND FOR /ssm/net/rpn/utils/15.2
ERROR: NO SHORTCUT FOUND FOR /ssm/net/rpn/libs/15.2
ERROR: NO SHORTCUT FOUND FOR /ssm/net/cmdn/vgrid/6.1.1/intel13sp1u2
ERROR: NO SHORTCUT FOUND FOR /ssm/net/hpcs/exp/aspgjdm/perftools
ERROR: NO SHORTCUT FOUND FOR /ssm/net/cmoi/base/20160901/
ERROR: NO SHORTCUT FOUND FOR ENV/rde/1.0.0
. .setenv.defaults.dot
./.setenv.dot: line 27: rdevar: command not found

**Comment by jeixav** [comment]
Are these errors produced after you issue `. ./.setenv.dot` in the Python-RPN directory? (They look like the definitions in [ssmusedep-dev.bndl](https://github.com/meteokid/python-rpn/blob/6b61c25fc1fbbb97537ea7835fc2732db3de1899/ssmusedep-dev.bndl).) I did not do that for issue https://github.com/meteokid/python-rpn/issues/9. I typed, at a regular command prompt independent of the command prompt where the bootstrap ran,

``` shell
export PYTHONPATH=~/local/src/python-rpn/lib
export LD_LIBRARY_PATH=~/ssm-domains-base/libs/rmnlib-dev/rmnlib-git_1.0_multi/lib/Linux_x86-64/gfortran
python
```

and at the Python prompt:

``` python
import rpnpy.librmn.all as rmn
```

Can you try that?

**Comment by doylejg** [comment]
Okay I am a few versions behind on the bootstrap it seems. I had grabbed the older version from an earlier post. 

With the new version and your corrections to burp.py in issue #10 I have it working.

Thanks for you help. Can we include this bootstrap in the main repo? It is a pain to have to consult the issues every time I install on a new machine.
