### ISSUE TITLE
Unable to open capital letter files with fstopenall

### ISSUE THREAD

**Issue by neishm** [meteokid/python-rpn#12]
If I have some standard file `XYZ`, I am unable to open it with fstopenall.  Sample code:
```
>>> f = rmn.fstopenall('XYZ', verbose=True)
(fstopenall) Not a RPNSTD file: XYZ
(fstopenall) Problem Opening: XYZ
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "rpnpy/librmn/fstd98.py", line 304, in fstopenall
    .format(str(paths)))
rpnpy.librmn.fstd98.FSTDError: fstopenall: unable to open any file in path ['XYZ']

```

Tested with 2.1.b2.

**Comment by jeixav** [comment]
@neishm I think you have access to the CMC Bugzilla. The issue resembles http://bugzilla.cmc.ec.gc.ca/show_bug.cgi?id=9893. Perhaps you want to add yourself to the CC list.

**Comment by neishm** [comment]
The underlying issue is the same - librmn has weird behaviour when the filename is all capitals.  There is one workaround from librmn, which is to prepend a `+` to the filename.  This gets treated as a special control character in librmn, telling it to preserve the letter case.

Unfortunately this workaround doesn't work in `rmn.fstopenall`, because then it thinks the file doesn't exist:
```
>>> f = rmn.fstopenall('+XYZ', verbose=True)
(fstopenall) File not found: +XYZ
(fstopenall) Problem Opening: +XYZ
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "rpnpy/librmn/fstd98.py", line 304, in fstopenall
    .format(str(paths)))
rpnpy.librmn.fstd98.FSTDError: fstopenall: unable to open any file in path ['+XYZ']
```
One fix is to modify `rpnpy.librmn.base.wkoffit` and `rpnpy.librmn.base.fnom` to prepend a `+` to the filename unconditionally (the character seems to get ignored when it's unnecessary).  I've tested the following patch on my end, and it seems to work:
```diff
diff --git a/lib/rpnpy/librmn/base.py b/lib/rpnpy/librmn/base.py
index fe1e8e9..90765fb 100755
--- a/lib/rpnpy/librmn/base.py
+++ b/lib/rpnpy/librmn/base.py
@@ -187,6 +187,7 @@ def fnom(filename, filemode=_rc.FST_RW, iunit=0):
     if not isinstance(filemode, str):
         raise TypeError("fnom: Expecting arg filemode of type str, Got {0}"\
                         .format(type(filemode)))
+    filename = '+'+filename
     istat = _rp.c_fnom(_ct.byref(ciunit), _C_WCHAR2CHAR(filename),
                        _C_WCHAR2CHAR(filemode), 0)
     istat = _C_TOINT(istat)
@@ -264,6 +265,7 @@ def wkoffit(filename):
                         "Got {0}".format(type(filename)))
     if filename.strip() == '':
         raise ValueError("wkoffit: must provide a valid filename")
+    filename = '+'+filename
     return _rp.c_wkoffit(_C_WCHAR2CHAR(filename), len(filename))
 
 
```
Result:
```
>>> f = rmn.fstopenall('XYZ', verbose=True)
(fstopenall) Opening: XYZ 999
```

**Comment by jeixav** [comment]
@neishm Looks like you are ready to submit a pull request!

**Comment by neishm** [comment]
For reference, the workaround triggers the following librmn code block: https://github.com/armnlib/librmn/blob/83a051f4cdaca54979a99c1d65532180d23ac223/primitives/c_baseio.c#L518-L524

As far as I know, this behaviour isn't documented anywhere...

**Comment by meteokid** [comment]
Good one. Thanks for catching this. I forgot legacy "fnom" behavior.
Does anyone know what happens to a filename actually starting with a '+'?
I'll look at you patch (pull request). Thanks!

**Comment by meteokid** [comment]
Merged into rpnpy_2.1-branch
