### ISSUE TITLE
Option to bypass fstprm when calling fstluk?

### ISSUE THREAD

**Issue by neishm** [meteokid/python-rpn#14]
For the scripts I'm working on, I only need the data (`'d'`) output from `fstluk`, not any of the record parameters from the header.  Profiling indicates the call to `fstprm` takes 10-20% of the read time in my usage, a non-negligible amount of time.  It would be useful (at least in my case) to have some optional argument to `fstluk` to bypass the `fstprm` call, e.g., to do something like
```python
rec = fstluk(funit, key, fstprm=False)  # Skips fstprm, only has 'd' and 'shape' entries.
```
Is this something that could be feasibly added to the package?

As an aside: is this issue page the best place to put feature requests, or is the internal bugzilla the preferred medium?

**Comment by jeixav** [comment]
Does `fstprm` need to be added as a new input parameter? `fstprm` is called to set `dtype`:
https://github.com/meteokid/python-rpn/blob/2d0c280700f1a9a79a72af453d576f62be7cc449/lib/rpnpy/librmn/fstd98.py#L1469-L1470

Could `fstluk` be revised so when `dtype` is given as an input argument, the call to `fstprm` is skipped?

It looks like `params['shape']` is also used in `fstluk` however.

**Comment by neishm** [comment]
Hmm... I hadn't thought about the `shape` parameter.  It's an output of `c_fstluk` (through ni,nj,nk), but you need to know it ahead of time for allocating the array.  So it's not as straight-forward as just disabling `fstprm`, you have to pass in this extra information somehow...

**Comment by meteokid** [comment]
Not sure about this one because of the above mentioned reasons that could create an inconsistency.
If need be the c_fstluk function in rpnpy.librmn.proto could be called directly.
If anyone see a strong case for adding this (considering c_fstluk), then please fee free to re-open this issue.

**Comment by neishm** [comment]
I agree, it's probably better to just call the c_fstluk function directly in this case.
