### ISSUE TITLE
Installation Outside CMC Intranet

### ISSUE THREAD

**Issue by jeixav** [meteokid/python-rpn#2]
To install python-rpn on a computer without access to the CMC intranet, I modifed installation steps. First, I executed http://scaweb.sca.uqam.ca/armnlib/repository/Linux_BOOTSTRAP-8.11-rmnlib15.2. Then I executed:

```
export SSM_DOMAIN_HOME=~/ssm-domains-base/setup/v_001
. ~/ECssm/etc/ssm.d/profile
. s.ssmuse.dot rmnlib-dev
export RPNPY_RMN_LIBPATH=~/ssm-domains-base/libs/rmnlib-dev/multi/lib/${EC_ARCH}/gfortran/
. ./.setenv.dot --dev
```

This allowed me to use fstopenall, fstinl and fstluk on a RPN Standard File. Should these steps be merged into https://github.com/meteokid/python-rpn/blob/master/README?

I also deleted these lines:
https://github.com/meteokid/python-rpn/blob/master/bin/.env_setup.dot#L68
https://github.com/meteokid/python-rpn/blob/master/ssmusedep-dev.bndl#L1

**Comment by doylejg** [comment]
The final command did not work for me 

``` bash
% . ./.setenv.dot --dev

-bash: ./.setenv.dot: No such file or directory
```

**Comment by jeixav** [comment]
@doylejg I can reproduce this error only if I intentionally move .setenv.dot:

```
$ mv .setenv.dot .setenv.dot.bak
$ . ./.setenv.dot --dev
-bash: ./.setenv.dot: No such file or directory
```

Does `ls -A` list [.setenv.dot](https://github.com/meteokid/python-rpn/blob/master/.setenv.dot)?

**Comment by doylejg** [comment]
Yes okay sorry I think I was in the lib directory. 

``` bash
$ . ./.setenv.dot --dev
Loading dev env: ssmusedep-dev.bndl
s.ssmuse.dot ENV/x/rde/1.0.rc5
WARNING: following item(s) not found:
 ENV/x/rde/1.0.rc5
Global tag values: 
ERROR: NO SHORTCUT FOUND FOR ENV/x/rde/1.0.rc5
touch: cannot touch `/home/ordenv/ssm-domains9/log/rpnpy-usage-2016-03.log': No such file or directory
-bash: /home/ordenv/ssm-domains9/log/rpnpy-usage-2016-03.log: No such file or directory
```

**Comment by jeixav** [comment]
Those errors should disappear if you delete these lines:
https://github.com/meteokid/python-rpn/blob/master/bin/.env_setup.dot#L68
https://github.com/meteokid/python-rpn/blob/master/ssmusedep-dev.bndl#L1

I think after commit 0e1692a971f3f27839eecec1b53365b5c66702fe, the first deletion should not be necessary.

**Comment by meteokid** [comment]
The README file has been updated for installtion outside CMC
A new README_CMC file was created to documents the CMC specific operations.
