### ISSUE TITLE
Some elements not being decoded in rpnpy.burpc?

### ISSUE THREAD

**Issue by neishm** [meteokid/python-rpn#20]
It appears that some types of burp elements aren't being decoded in `rpnpy.burpc`.  Instead, the `e_rval` array holds some random values (from uninitialized memory?).

Example of triggering this problem:

```python
import rpnpy.librmn.all as rmn
import rpnpy.burpc.all as brp
import os
mypath = os.path.join(os.environ['ATM_MODEL_DFILES'],'bcmk_burp','2007021900.brp')
with brp.BurpcFile(mypath) as bfile:
  rpt = bfile[0]
  blk = rpt[1]
  for i, ele in enumerate(blk):
    print 'ELE', i
    print ele
```

When I run this test on the science network, the "ELE 6" e_rval changes every time I run the script.  The only differences I can see with this element is it has `e_cvt` set to 0 (no conversion?).  This issue is present in both `2.1.b3` and on the latest master branch.

This was causing sporadic failures for me in the `test_brp_blk_getele_iter` unit test - if the garbage values happen to have a `nan` in there, then the `==` comparison would fail.  This only happened once in a while, so it took a while to figure out why tests that _were_ working suddenly failed... fun times.

**Comment by meteokid** [comment]
Thanks for checking into this.

This was fixed in the current development branch (rpnpy_2.1-branch; we'll update the master branch once we release version 2.1). 
I think this was related to a problem when dealing with missing values (-1) (a few commits last March and April).

I  ran an infinite loop with your test script making diff with the previous iter... it's been almost 30min getting no diff.

Modifying your test script to only print when e_cvt==0, I get consistently:
```
 UNITE = 999 FICHIER RAPPORT EST OUVERT
 MRFLOC- TROUVE - STNID=71915     IDTYP=138 LAT=15420 LON=27663 DX=   0 DY=   0 DATE=20070219 TEMPS=   0 FLGS=   72706 LNGR=   746
RECORD READ
ELE 6
BurpcEle({'store_type': 'F', 'shape': (17, 1), 'e_drval': None, 'e_rval': array([[-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.]], dtype=float32), 'e_bias': 0, 'e_error': 0, 'e_charval': None, 'e_bufrid_F': 0, 'e_desc': 'VERTICAL SOUNDING SIGNIFICANCE', 'e_nbits': 7, 'e_bufrid_Y': 1, 'e_bufrid_X': 8, 'e_bufrid': 8001, 'nt': 1, 'e_tblval': array([[-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1],
       [-1]], dtype=int32), 'e_ival': None, 'e_scale': 0, 'nval': 17, 'ptrkey': 'e_rval', 'e_cmcid': 2049, 'e_units': 'FLAG TABLE', 'e_multi': 0, 'e_cvt': 0})

 UNITE = 999 FICHIER RAPPORT EST FERME
```

Please re-open this issue if you can still trigger that problem with the latest dev code.

**Comment by neishm** [comment]
Thanks! I can confirm that `rpnpy_2.1-branch` resolves the issue I was having.
