### ISSUE TITLE
fstopenall not linking files properly

### ISSUE THREAD

**Issue by davidlandry93** [meteokid/python-rpn#24]
When using `fstopenall` with an array of standard files, records beyond the first file are not accessible. I wrote a little reproduction script. Can you guys reproduce? I found this issue on PPP2 and my local machine.

```python
import pathlib

import rpnpy.librmn.all as rmn

FST_PATH = pathlib.Path('/space/hall2/sitestore/eccc/cmod/prod/hubs/gridpt/dbase/caldas/hrdps_national/analysis/final/diag')

if __name__ == '__main__':
    fsts = list((str(x) for x in FST_PATH.iterdir() if rmn.isFST(str(x))))[0:2]

    print('Running test on two standard files: {}'.format(fsts))

    first_fst = rmn.fstopenall(fsts[0])
    first_fst_n_records = rmn.fstnbr(first_fst)
    rmn.fstcloseall(first_fst)

    second_fst = rmn.fstopenall(fsts[1])
    second_fst_n_records = rmn.fstnbr(second_fst)
    rmn.fstcloseall(second_fst)

    merged_fst = rmn.fstopenall(fsts)
    merged_fst_n_records = rmn.fstnbr(merged_fst)
    rmn.fstcloseall(merged_fst)

    # The following assert fails with rpnpy 2.1.b3 on ppp2
    assert(merged_fst_n_records == first_fst_n_records + second_fst_n_records)
```

**Comment by meteokid** [comment]
Python-RPN is mainly a python interface to C/Fortran functions in librmn.  
Is this a librmn issue (with `fstlnk` or `fstnbr`) or a Python-RPN one?

**Comment by neishm** [comment]
This looks like a known deficiency with `fstnbr`.  Found a comment about it in the unit tests:
https://github.com/meteokid/python-rpn/blob/ed4f4f608bba24ee277eebfbebfd2ff7ce2860b6/share/tests/test_librmn_fstd98.py#L166-L168

**Comment by neishm** [comment]
Calling `rmn.fstinl(merged_fst)` returns a list of 8 record keys for me, which I think is the expected number from both files.

**Comment by meteokid** [comment]
I confirm that replacing `rmn.fstnbr(...)` by `len(rmn.fstinl(...))` the number adds up and the test succeeds.  
Thanks Micheal.

This problem is thus a known bug of `fstnbr` in librmn itself (not Python-RPN).  
I'll report it to the developers.  
And I'll update the known issue.

**Comment by meteokid** [comment]
The feature has been implemented in the python layer. It will be part of version 2.1.0
