### ISSUE TITLE
Issue importing 'all'

### ISSUE THREAD

**Issue by doylejg** [meteokid/python-rpn#3]
While attempting

``` python
import rpnpy.librmn.all as rmn
```

I get the following traceback

``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/git/python-rpn/lib/rpnpy/librmn/__init__.py", line 31, in <module>
    from rpnpy.version import *
ImportError: No module named version
```

Is this a missing package or have I set something up wrong?

**Comment by jeixav** [comment]
I think I forgot this in https://github.com/meteokid/python-rpn/issues/2. I think I made a copy of lib/rpnpy/version.py by hand:

```
__VERSION__ = '2.0.dev'
__LASTUPDATE__ = '2016-03-04 12:18 EST'
```

**Comment by meteokid** [comment]
The creation of the rpnpy.version file is now documented in the README file
