### ISSUE TITLE
Running units tests external to CMC

### ISSUE THREAD

**Issue by doylejg** [meteokid/python-rpn#6]
So I'm back to trying to install python-rpn on a CMC external computer. After following the steps outlined in Issue #2, with the following changes:
- removed all lines in  https://github.com/meteokid/python-rpn/blob/master/ssmusedep-dev.bndl
- removed line 71 rather than 68 https://github.com/meteokid/python-rpn/blob/master/bin/.env_setup.dot#L71

When running the tests I encounter the following issues:

The directories are not accessible externally so the tests are not portable:
- /home/ordenv/ssm-domains9/release/gem-data_4.2.0/gem-data_4.2.0_all/...
- /users/dor/armn/env/SsmBundles/GEM/d/gem-data/gem-data_4.2.0/gem-data_4.2.0_all/...

The following three tests fail independantly (I think) of the missing files. 

``` python
======================================================================
ERROR: test_14 (__main__.rpnpyCookbook)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "share/tests/test_cookbook.py", line 342, in test_14
    import rpnpy.vgd.all as vgd
  File "/home/doyle/git/rpnpy/lib/rpnpy/vgd/__init__.py", line 102, in <module>
    (VGD_VERSION, VGD_LIBPATH, libvgd) = loadVGDlib()
  File "/home/doyle/git/rpnpy/lib/rpnpy/vgd/__init__.py", line 90, in loadVGDlib
    raise IOError(-1, 'Failed to find libdescrip.so: ', vgd_libfile)
IOError: [Errno -1] Failed to find libdescrip.so: : 'libdescripshared_6.0.0.so'

======================================================================
ERROR: test_22 (__main__.rpnpyCookbook)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "share/tests/test_cookbook.py", line 608, in test_22
    sys.stderr.write("Problem opening the files: %s, %s\n" % (fileNameIn, fileNameOut))
NameError: global name 'sys' is not defined

======================================================================
ERROR: testfnomfclosKnownValues (__main__.LibrmnFilesKnownValues)
fnomfclos should give known result with known input
----------------------------------------------------------------------
Traceback (most recent call last):
  File "share/tests/test_librmn_base.py", line 33, in testfnomfclosKnownValues
    iout  = rmn.fnom(mypath,rmn.FST_RO)
  File "/home/doyle/git/rpnpy/lib/rpnpy/librmn/base.py", line 147, in fnom
    raise RMNBaseError()
RMNBaseError

```

**Comment by jeixav** [comment]
See https://gitlab.com/ECCC_CMDN/vgrid for the vgrid source code. It should allow compiling libdescripshared_6.0.0.so, for test_14.

**Comment by meteokid** [comment]
Thanks Kristjan (jeixav) for answering relative to the missing libdescrip.s (vgrid) erro.

About the 2 other errors:
- File "share/tests/test_cookbook.py", line 608, in test_22: 
  A fix from guziy has just been merged.
- File "share/tests/test_librmn_base.py", line 33, in testfnomfclosKnownValues
  Unfortunately this test an a few other uses big data files that we cannot easily export.
  We'd have to think about a way to boot strap these tests by locally creating test data files.

**Comment by jeixav** [comment]
> ... We'd have to think about a way to boot strap these tests by locally creating test data files.

@meteokid, [git-annex](http://git-annex.branchable.com/) and [Git Large File Storage](https://git-lfs.github.com/) should enable binary file references in unit tests, if you have not already thought about them.

There seem to be science data repositories that could host test data-sets, here is a list: http://www.nature.com/sdata/policies/repositories#envgeo.

In a hallway conversation, @mfvalin seemed receptive to hosting data under http://scaweb.sca.uqam.ca/armnlib/repository/ as well. However he would want test files just big enough to test Python-RPN functionality.

**Comment by jeixav** [comment]
> Unfortunately this test an a few other uses big data files that we cannot easily export.

I've uploaded the GEM data SSM to http://collaboration.cmc.ec.gc.ca/science/ssm/gem-data_4.2.0_all.ssm. Untar this file and I think it will provide the required data files for python-rpn unit tests.
