### ISSUE TITLE
cleanName

### ISSUE THREAD

**Issue by ngasset** [meteokid/python-rpn#8]
Salut,

dans la routines
bin/rpy.nml_set 
bin/rpy.nml_get 
Il y a un appel a "cleanname" or cleanname n est declarer nulle part. 
Ca mene donc a une erreur.

Dans la cas de bin/rpy.nml_set, ne suffirai t'il pas de commenter la ligne (sa semble un oublie?). En tout cas, cette fonction redevient fonctionnel une fois cette ligne commentée.

Merci

**Comment by meteokid** [comment]
Fixed
cleanname was made private in the ftnnml module
fix as to add it back in rpy.nml_get/set scripts
Commited in the python-rpn_2.0-branch
